spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/jamsGit/ConfigData
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:9005/eureka/
server:
  port: 8080
  